### ISSUE TITLE
display of Researcher's ORCiD in DataCite metadata

### ISSUE THREAD

**Issue by ajmclean** [datacite/search#148]
Hello, I raised a bug last year regarding ORCiDs display in DataCite. An example of the problem is easiest illustrated with the following example:

	Looking at http://data.datacite.org/10.14469/HPC/1280  and the metadata 

	Contributors/Researcher,  James Clarke 0000-0002-8635-8390

There is nothing in this entry that identifies 0000-0002-8635-8390  as an  ORCID, no link or other information.

Can you advise on how this linkage between researcher's name and ORCiD should be done, and whether the DataCite bug that was present is now fixed?

Thanks, Andrew

**Comment by mfenner** [comment]
The DataCite metadata for `10.14469/HPC/1280` are pretty clear, and follow our recommendations:
```
<nameIdentifier schemeURI="http://orcid.org" nameIdentifierScheme="ORCID">0000-0002-8635-8390</nameIdentifier>
```

I am not clear what needs to be fixed or where there is a bug. Do you refer to the HTML presentation of this metadata record that you see at http://data.datacite.org/10.14469/HPC/1280? The nameIdentifierScheme is not displayed and we should add that.

**Comment by hrzepa** [comment]
Yes, "The nameIdentifierScheme is not displayed and we should add that" is what is at issue.  It is the "human readable" presentation that is unclear;  the XML version  DOES contain the information.

**Comment by mfenner** [comment]
Thanks for the clarification. I will update the HTML representation. Content negotiation is done by the [Content resolver](https://github.com/datacite/content-resolver) service, so I will track the issue in that Github repo.

**Comment by ajmclean** [comment]
Martin, yes, this is a presentational thing. Is it possible to hyperlink the ORCiD associated with the author. Along the lines of
                [cid:image001.png@01D202A7.680D45E0]

Regards, Andrew
