### ISSUE TITLE
Download of application/x-datacite+xml

### ISSUE THREAD

**Issue by hrzepa** [datacite/search#149]
Invoking eg http://data.datacite.org/content-resolver/application/x-datacite+xml/10.14469/HPC/1280 or http://data.datacite.org/application/x-datacite+xml/10.14469/HPC/1280
 downloads a file with no suffix (.xml would be appropriate in this context). 

Could a filename suffix be added to the download. This serves to disambiguate downloads, which otherwise all end up being named eg  1280.

**Comment by mfenner** [comment]
This behavior seems to be browser-dependent, see for example 

```
curl http://data.datacite.org/content-resolver/application/x-datacite+xml/10.14469/HPC/1280
```

Will investigate a generic solution, but not until we do a relaunch of `text/html` content negotiation.

**Comment by mfenner** [comment]
This has been fixed in the relaunched DOI content negotation: https://github.com/crosscite/content-negotiation/blob/master/config/initializers/mime_types.rb#L35-L42

Blog post announcing new DOI content negotiation:  https://blog.datacite.org/content-negotiation-update/
