### ISSUE TITLE
how to access classic meta page

### ISSUE THREAD

**Issue by elliewix** [datacite/search#150]
Apologies if this issue is being placed in the incorrect repo.  This issue seems to span over several resources, and I'm happy to migrate it to a more appropriate repo.

In sum: we can no longer access the 'classic' meta page (from http://data.datacite.org) where the fuller datacite metadata is represented, which is disruptive to our workflows.  Can we still get to it somewhere?  If no, please take this as a feature request issue for the new meta page.

The longer story:

We at UIUC often need to access meta pages for our DOIs.  We used to go to http://data.datacite.org/10.13012/restofdoistuff to view this page.  I know that the new search has a new version of the meta page (example: https://search.datacite.org/works/10.13012/J8TD9V7M) but it displays a very limited version of the metadata and thus is not useful to us.  We've been using the classic version because it shows related identifiers, alternative identifiers, raw license text, etc.  I understand that the raw XML can be accessed from this new page, but we're often reviewing many of these on a regular basis and being required to download the XML each time is substantial hassle.  

I'm filing this issue because it looks like the classic meta page now just redirects to the DOI target, but the link still remains on the stats.datacite.org page (in the "top 10" panel).  So either that link needed to be updated to the new meta page, or the redirect is not an intended feature.  Or something else, of course.  

But we'd like either the classic page back or to have additional metadata elements represented on the new meta page.

**Comment by mfenner** [comment]
@elliewix thanks a lot for opening the issue. We are aware that the recently released update of the content negotiation service is a breaking change, and we mentioned this in the announcement blog post at https://blog.datacite.org/content-negotiation-update/.

The reason that the "classic meta page" disappeared is that this page had nothing to do with content negotiation, it was just a way to show the metadata on a web page. There were some serious limitations of this implementations, so we started to implement the functionality in DataCite Search a while ago. We are aware that there are missing metadata, and we will be adding all the functionality to DataCite Search pages for individual DOIs going forward - the transition should be complete in two months.

The code that displays the metadata in DataCite Search is at https://github.com/crosscite/doi-metadata-search, but that is not important.
