### ISSUE TITLE
SOLR indexing has not been trigger in the last 6 days

### ISSUE THREAD

**Issue by kjgarza** [datacite/search#163]
As a result the REST API is not updated

**Comment by kjgarza** [comment]
[Uploading Bildschirmfoto 2018-03-02 um 10.59.37.png...]

**Comment by kjgarza** [comment]
![screenshot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5936775a17ad63001a910f29/125516c66e82c728ace21e0d46fb978826878dba87e6ab01e81fe086264c22703d46f96925dcb12de6162d585f5c4ffd105b5f44ffac8f78f5b63d25984019af80330b2b9b645bf9fa9015ad00b32a8a4a84bfb58f45c9e9352ce78d9d02.png)

**Comment by fumi** [comment]
It seems that the API has not been updated again since 12 Mar. 2018.

**Comment by richardhallett** [comment]
Some internal work on our infrastructure over at https://github.com/datacite/mastino should have fixed our solr rebuild problem, closing for now.
